spring:
  application:
    name: apipedido
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dbpedido
    username: sa
    password: password
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect